name: Linux

on: [push]

jobs:
  build:
    name: Build for ${{ matrix.os }}:${{ matrix.version }} (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu
            version: "22.04"
            arch: amd64
          - os: ubuntu
            version: "22.04"
            arch: arm64
          - os: alpine
            version: "3.19"
            arch: amd64
          - os: alpine
            version: "3.19"
            arch: arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build in Docker container
      run: |
        docker run --rm --platform linux/${{ matrix.arch }} -v "${{ github.workspace }}":/workdir -w /workdir \
          ${{ matrix.os }}:${{ matrix.version }} \
          /bin/sh -c ' \
            if [ "${{ matrix.os }}" = "ubuntu" ]; then \
              apt-get -y update && apt-get -y install build-essential; \
            else \
              apk add linux-headers build-base; \
            fi && \
            cd src && \
            make && \
            mkdir build && \
            cp wg ./build/awg && \
            cp wg-quick/linux.bash ./build/awg-quick \
          '

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.version }}-amneziawg-tools-${{ matrix.arch }}
        path: ./src/build

  release:
    name: GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip files
        run: |
          for dir in artifacts/*; do
            if [ -d "$dir" ]; then
              zip -j "${dir}.zip" "${dir}"/*
            fi
          done

      - name: Upload binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*.zip
          tag: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
